### ISSUE TITLE
Drizzle Partial Select not possible

### ISSUE THREAD

**Issue by Lennart-Franck** [Atinux/nuxt-guestbook#1]
Because the way Drizzle is initialized, it is somehow not possible to do partial selects with drizzle. Is there somehow a nice workaround to get this working? I am using the same setup in a project of mine and running in this issue. Also, would it be possible to provide drizzle with the schema, so the query syntax is working?

Thank you for this nice template!

**Comment by atinux** [comment]
Could you give me an example of partial selects @Lennart-Franck ?

**Comment by Lennart-Franck** [comment]
Of course @Atinux, just the plain partial select as seen in the drizzle documentation: https://orm.drizzle.team/docs/select#partial-select

**Comment by atinux** [comment]
Well from what I see:

```ts
const result = await db.select({
  field1: users.id,
  field2: users.name,
}).from(users);
 ```

Can become:
```ts
const result = await useDB().select({
  field1: tables.users.id,
  field2: tables.users.name,
}).from(users);
 ```

**Comment by Lennart-Franck** [comment]
If i use it for example like that:
```ts
export default eventHandler(() => {
  return useDB().select({
    authorName: tables.comments.author
  }).from(tables.comments)
})
```

I get the following error: 
`Expected 0 arguments, but got 1.`

**Comment by atinux** [comment]
Well you need to call .all() at the end

**Comment by Lennart-Franck** [comment]
Still getting the error when I use the following code:
```ts
export default eventHandler(() => {
  return useDB().select({
    authorName: tables.comments.author
  }).from(tables.comments).all()
})
```

**Comment by atinux** [comment]
Oh well it seems to be a TS error, the code works though right? (tested locally and it works)

**Comment by Lennart-Franck** [comment]
Okay, firstly, thank you very much for taking your time with me @Atinux! And second, yeah, it looks like a TS error because the code gets executed. Do you maybe know how to fix this TS error?

**Comment by atinux** [comment]
Sadly I have no idea, drizzle should actually handle this 🤔
