### ISSUE TITLE
Demo app is not working

### ISSUE THREAD

**Issue by alexchexes** [Atinux/nuxt-guestbook#4]
Trying to add a comment produces a 500 server error:
![image](https://github.com/Atinux/nuxt-guestbook/assets/49966773/adf7510e-91a3-4d64-8610-af27b47b03da)

By the way it would be nice to add an "Add" button, as now it is not obvious that to add a comment you need to unfocus the input field.

**Comment by atinux** [comment]
It's good now :)

Thanks for the report!
